name: twin_peaks_tv
description: "Demo application of the Flutter plugin tv_plus"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tv_plus: ^0.0.2
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  auto_route: ^11.1.0
  freezed: ^3.2.4
  freezed_annotation: ^3.0.0
  rx_shared_preferences: ^4.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  fast_immutable_collections: ^11.1.0
  dartx: ^1.2.0
  bloc_presentation: ^1.1.2
  rxdart: ^0.28.0
  dio: ^5.9.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.12.0
  flutter_pre_commit: ^0.2.4
  build_runner: ^2.10.5
  injectable_generator: ^2.12.0
  auto_route_generator: ^10.4.0
#  json_serializable: ^6.11.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
